add(c2, c1, c14);
add(c2, -c1, -c14);
add(-c2, -c1, c14);
add(-c2, c1, -c14);

add(c14, c2, c1);
add(c14, -c2, -c1);
add(-c14, -c2, c1);
add(-c14, c2, -c1);

add(c1, c14, c2);
add(c1, -c14, -c2);
add(-c1, -c14, c2);
add(-c1, c14, -c2);

add(c3, -c4, c13);
add(c3, c4, -c13);
add(-c3, c4, c13);
add(-c3, -c4, -c13);

add(c13, -c3, c4);
add(c13, c3, -c4);
add(-c13, c3, c4);
add(-c13, -c3, -c4);

add(c4, -c13, c3);
add(c4, c13, -c3);
add(-c4, c13, c3);
add(-c4, -c13, -c3);

add(c0, c8, c12);
add(c0, -c8, -c12);
add(-c0, -c8, c12);
add(-c0, c8, -c12);

add(c12, c0, c8);
add(c12, -c0, -c8);
add(-c12, -c0, c8);
add(-c12, c0, -c8);

add(c8, c12, c0);
add(c8, -c12, -c0);
add(-c8, -c12, c0);
add(-c8, c12, -c0);

add(c7, c6, c11);
add(c7, -c6, -c11);
add(-c7, -c6, c11);
add(-c7, c6, -c11);

add(c11, c7, c6);
add(c11, -c7, -c6);
add(-c11, -c7, c6);
add(-c11, c7, -c6);

add(c6, c11, c7);
add(c6, -c11, -c7);
add(-c6, -c11, c7);
add(-c6, c11, -c7);

add(c9, -c5, c10);
add(c9, c5, -c10);
add(-c9, c5, c10);
add(-c9, -c5, -c10);

add(c10, -c9, c5);
add(c10, c9, -c5);
add(-c10, c9, c5);
add(-c10, -c9, -c5);

add(c5, -c10, c9);
add(c5, c10, -c9);
add(-c5, c10, c9);
add(-c5, -c10, -c9);