// V0-V3
add(c2, c1, c14);
add(c2, -c1, -c14);
add(-c2, -c1, c14);
add(-c2, c1, -c14);
// V4-V7
add(c14, c2, c1);
add(c14, -c2, -c1);
add(-c14, -c2, c1);
add(-c14, c2, -c1);
// V8-V11
add(c1, c14, c2);
add(c1, -c14, -c2);
add(-c1, -c14, c2);
add(-c1, c14, -c2);
// V12-V15
add(c3, -c4, c13);
add(c3, c4, -c13);
add(-c3, c4, c13);
add(-c3, -c4, -c13);
// V16-V19
add(c13, -c3, c4);
add(c13, c3, -c4);
add(-c13, c3, c4);
add(-c13, -c3, -c4);
// V20-V23
add(c4, -c13, c3);
add(c4, c13, -c3);
add(-c4, c13, c3);
add(-c4, -c13, -c3);
// V24-V27
add(c0, c8, c12);
add(c0, -c8, -c12);
add(-c0, -c8, c12);
add(-c0, c8, -c12);
// V28-V31
add(c12, c0, c8);
add(c12, -c0, -c8);
add(-c12, -c0, c8);
add(-c12, c0, -c8);
// V32-V35
add(c8, c12, c0);
add(c8, -c12, -c0);
add(-c8, -c12, c0);
add(-c8, c12, -c0);
// V36-V39
add(c7, c6, c11);
add(c7, -c6, -c11);
add(-c7, -c6, c11);
add(-c7, c6, -c11);
// V40-V43
add(c11, c7, c6);
add(c11, -c7, -c6);
add(-c11, -c7, c6);
add(-c11, c7, -c6);
// V44-V47
add(c6, c11, c7);
add(c6, -c11, -c7);
add(-c6, -c11, c7);
add(-c6, c11, -c7);
// V48-V51
add(c9, -c5, c10);
add(c9, c5, -c10);
add(-c9, c5, c10);
add(-c9, -c5, -c10);
// V52-V55
add(c10, -c9, c5);
add(c10, c9, -c5);
add(-c10, c9, c5);
add(-c10, -c9, -c5);
// V56-V59
add(c5, -c10, c9);
add(c5, c10, -c9);
add(-c5, c10, c9);
add(-c5, -c10, -c9);